/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Controleur.CtrlImprimerOrdonnance;
import Controleur.CtrlSupprimerPatient;
import Controleur.CtrlSupprimerRDV;
import connexion.connexionBD;
import java.awt.*;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ghada
 */
public class FenPrincipale extends javax.swing.JFrame {
    
   
    
    public FenPrincipale(int idm) {
        initComponents();
        this.idm = idm;
        dt = new DefaultTableModel();
        remplirtableMalade();
        tableMalade.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent event) {
                remplirTableRdvByTableMalade();
                tableRDV.getSelectionModel().setSelectionInterval(0, 0);
            }
        });
        tableMalade.getSelectionModel().setSelectionInterval(0, 0);
        tableRDV.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent event) {
                afficheInfosConsultationByTableRDV();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        btImprimerOrdonnance = new javax.swing.JButton();
        btAjouterMalade = new javax.swing.JButton();
        btAjouterRDV = new javax.swing.JButton();
        btModifierRDV = new javax.swing.JButton();
        btModifierMalade = new javax.swing.JButton();
        btSupprimerMalade = new javax.swing.JButton();
        btSupprimerRDV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTraitement = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtMotif = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtResExamClinique = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtResExamParaclinique = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtDiagnostic = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboFiltre = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtFiltre = new javax.swing.JTextField();
        btFiltrer = new javax.swing.JButton();
        btAnnulerFiltre = new javax.swing.JButton();
        jScrollTableRDV = new javax.swing.JScrollPane();
        tableRDV = new javax.swing.JTable();
        jScrollTableMalade = new javax.swing.JScrollPane();
        tableMalade = new javax.swing.JTable();
        btAjouterConsultation = new javax.swing.JButton();
        btModifierConsultation = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuItemParamImp = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemQuitter = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemAjouterMalade = new javax.swing.JMenuItem();
        menuItemModifierMalade = new javax.swing.JMenuItem();
        menuItemSupprimerMalade = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuItemAjouterRDV = new javax.swing.JMenuItem();
        menuItemModifierRDV = new javax.swing.JMenuItem();
        menuItemSupprimerRDV = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemAjouterConsultation = new javax.swing.JMenuItem();
        menuItemModifierConsultation = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemOrdonnance = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Cabinet Medical"); // NOI18N

        jPanel1.setLayout(null);

        btImprimerOrdonnance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Print.gif"))); // NOI18N
        btImprimerOrdonnance.setText("Imprimer Ordonnance");
        btImprimerOrdonnance.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btImprimerOrdonnance.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btImprimerOrdonnance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimerOrdonnanceActionPerformed(evt);
            }
        });
        jPanel1.add(btImprimerOrdonnance);
        btImprimerOrdonnance.setBounds(850, 0, 130, 30);

        btAjouterMalade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/New document.gif"))); // NOI18N
        btAjouterMalade.setText("Ajouter Malade");
        btAjouterMalade.setToolTipText("");
        btAjouterMalade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btAjouterMalade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAjouterMalade.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btAjouterMalade.setIconTextGap(0);
        btAjouterMalade.setName("btAjouterMalade"); // NOI18N
        btAjouterMalade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterMaladeActionPerformed(evt);
            }
        });
        jPanel1.add(btAjouterMalade);
        btAjouterMalade.setBounds(0, 0, 100, 30);
        btAjouterMalade.getAccessibleContext().setAccessibleName("btAjouterMalade");
        btAjouterMalade.getAccessibleContext().setAccessibleDescription("btAjouterMalade");

        btAjouterRDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/New document.gif"))); // NOI18N
        btAjouterRDV.setText("Ajouter RDV");
        btAjouterRDV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btAjouterRDV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAjouterRDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterRDVActionPerformed(evt);
            }
        });
        jPanel1.add(btAjouterRDV);
        btAjouterRDV.setBounds(580, 0, 90, 30);

        btModifierRDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Modify.gif"))); // NOI18N
        btModifierRDV.setText("Modifier RDV");
        btModifierRDV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btModifierRDV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btModifierRDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifierRDVActionPerformed(evt);
            }
        });
        jPanel1.add(btModifierRDV);
        btModifierRDV.setBounds(670, 0, 87, 30);

        btModifierMalade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Modify.gif"))); // NOI18N
        btModifierMalade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btModifierMalade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btModifierMalade.setLabel("Modifier Malade");
        btModifierMalade.setName("btModifierMalade"); // NOI18N
        btModifierMalade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifierMaladeActionPerformed(evt);
            }
        });
        jPanel1.add(btModifierMalade);
        btModifierMalade.setBounds(100, 0, 101, 30);

        btSupprimerMalade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Delete.gif"))); // NOI18N
        btSupprimerMalade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btSupprimerMalade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSupprimerMalade.setLabel("Supprimer Malade");
        btSupprimerMalade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprimerMaladeActionPerformed(evt);
            }
        });
        jPanel1.add(btSupprimerMalade);
        btSupprimerMalade.setBounds(200, 0, 120, 30);

        btSupprimerRDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Delete.gif"))); // NOI18N
        btSupprimerRDV.setText("Supprimer RDV");
        btSupprimerRDV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btSupprimerRDV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSupprimerRDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprimerRDVActionPerformed(evt);
            }
        });
        jPanel1.add(btSupprimerRDV);
        btSupprimerRDV.setBounds(757, 0, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Traitement Préscrit :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(710, 390, 180, 14);

        txtTraitement.setColumns(20);
        txtTraitement.setRows(5);
        txtTraitement.setName("txtTraitement"); // NOI18N
        jScrollPane2.setViewportView(txtTraitement);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(710, 410, 400, 130);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Motif de consultation :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 390, 140, 14);

        txtMotif.setColumns(20);
        txtMotif.setRows(5);
        txtMotif.setFocusCycleRoot(true);
        txtMotif.setName("txtMotif"); // NOI18N
        jScrollPane5.setViewportView(txtMotif);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(10, 410, 320, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Resultat de l'examen clinique :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 480, 190, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Diagnostic Médical :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 390, 180, 14);

        txtResExamClinique.setColumns(20);
        txtResExamClinique.setRows(5);
        txtResExamClinique.setName("txtResExamClinique"); // NOI18N
        jScrollPane6.setViewportView(txtResExamClinique);

        jPanel1.add(jScrollPane6);
        jScrollPane6.setBounds(10, 500, 320, 70);

        txtResExamParaclinique.setColumns(20);
        txtResExamParaclinique.setRows(5);
        txtResExamParaclinique.setName("txtResExamParaclinique"); // NOI18N
        jScrollPane8.setViewportView(txtResExamParaclinique);

        jPanel1.add(jScrollPane8);
        jScrollPane8.setBounds(360, 500, 310, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Resultats des examens paracliniques :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 480, 220, 14);

        txtDiagnostic.setName("txtDiagnostic"); // NOI18N
        txtDiagnostic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiagnosticActionPerformed(evt);
            }
        });
        jPanel1.add(txtDiagnostic);
        txtDiagnostic.setBounds(360, 410, 310, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Source de filtre :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 40, 100, 14);

        comboFiltre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nom", "Prenom" }));
        comboFiltre.setName("comboFiltre"); // NOI18N
        jPanel1.add(comboFiltre);
        comboFiltre.setBounds(120, 40, 100, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Text de filtre :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 40, 80, 14);

        txtFiltre.setName("txtFiltre"); // NOI18N
        jPanel1.add(txtFiltre);
        txtFiltre.setBounds(320, 40, 190, 20);

        btFiltrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Filter.gif"))); // NOI18N
        btFiltrer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btFiltrer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btFiltrer.setLabel("Filtrer");
        btFiltrer.setName("btFiltrer"); // NOI18N
        jPanel1.add(btFiltrer);
        btFiltrer.setBounds(520, 40, 60, 23);

        btAnnulerFiltre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Cancel.gif"))); // NOI18N
        btAnnulerFiltre.setText("Annuler Filtre");
        btAnnulerFiltre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btAnnulerFiltre);
        btAnnulerFiltre.setBounds(583, 40, 140, 25);

        jScrollTableRDV.setName("jScrollTableRDV"); // NOI18N

        tableRDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date RDV", "Numero RDV"
            }
        ));
        tableRDV.setName("tableRDV"); // NOI18N
        jScrollTableRDV.setViewportView(tableRDV);

        jPanel1.add(jScrollTableRDV);
        jScrollTableRDV.setBounds(880, 70, 250, 310);

        jScrollTableMalade.setName("jScrollTableMalade"); // NOI18N

        tableMalade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Prenom", "Date Naissance", "Telephone", "Sexe", "Situation familiale", "Profession", "Assuré", "Adresse"
            }
        ));
        tableMalade.setName("tableMalade"); // NOI18N
        jScrollTableMalade.setViewportView(tableMalade);

        jPanel1.add(jScrollTableMalade);
        jScrollTableMalade.setBounds(11, 70, 850, 310);

        btAjouterConsultation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/New document.gif"))); // NOI18N
        btAjouterConsultation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btAjouterConsultation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAjouterConsultation.setLabel("Ajouter Consultation");
        btAjouterConsultation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterConsultationActionPerformed(evt);
            }
        });
        jPanel1.add(btAjouterConsultation);
        btAjouterConsultation.setBounds(320, 0, 130, 30);

        btModifierConsultation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Modify.gif"))); // NOI18N
        btModifierConsultation.setText("Modifier Consultation");
        btModifierConsultation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btModifierConsultation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btModifierConsultation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifierConsultationActionPerformed(evt);
            }
        });
        jPanel1.add(btModifierConsultation);
        btModifierConsultation.setBounds(450, 0, 130, 30);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/List.gif"))); // NOI18N
        jMenu1.setText("Fichier");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Go back.gif"))); // NOI18N
        jMenuItem1.setText("Deconnecter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuItemParamImp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Wrench.gif"))); // NOI18N
        menuItemParamImp.setText("Parametres de l'impression");
        menuItemParamImp.setName("menuItemParamImp"); // NOI18N
        jMenu1.add(menuItemParamImp);
        jMenu1.add(jSeparator1);

        menuItemQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Cancel.gif"))); // NOI18N
        menuItemQuitter.setText("Quitter");
        menuItemQuitter.setName("menuItemQuitter"); // NOI18N
        menuItemQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemQuitterActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemQuitter);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Folder.gif"))); // NOI18N
        jMenu2.setText("Malade");

        menuItemAjouterMalade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/New document.gif"))); // NOI18N
        menuItemAjouterMalade.setText("Ajouter Malade");
        menuItemAjouterMalade.setName("menuItemAjouterMalade"); // NOI18N
        menuItemAjouterMalade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAjouterMaladeActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemAjouterMalade);

        menuItemModifierMalade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Modify.gif"))); // NOI18N
        menuItemModifierMalade.setText("Modifier Malade");
        menuItemModifierMalade.setName("menuItemModifierMalade"); // NOI18N
        menuItemModifierMalade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModifierMaladeActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemModifierMalade);

        menuItemSupprimerMalade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Delete.gif"))); // NOI18N
        menuItemSupprimerMalade.setText("Supprimer Malade");
        menuItemSupprimerMalade.setName("menuItemSupprimerMalade"); // NOI18N
        menuItemSupprimerMalade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSupprimerMaladeActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemSupprimerMalade);

        jMenuBar1.add(jMenu2);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Folder.gif"))); // NOI18N
        jMenu5.setText("RDV");

        menuItemAjouterRDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/New document.gif"))); // NOI18N
        menuItemAjouterRDV.setText("Ajouter RDV");
        menuItemAjouterRDV.setName("menuItemAjouterRDV"); // NOI18N
        menuItemAjouterRDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAjouterRDVActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemAjouterRDV);

        menuItemModifierRDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Modify.gif"))); // NOI18N
        menuItemModifierRDV.setText("Modifier RDV");
        menuItemModifierRDV.setName("menuItemModifierConsultation"); // NOI18N
        menuItemModifierRDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModifierRDVActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemModifierRDV);

        menuItemSupprimerRDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Delete.gif"))); // NOI18N
        menuItemSupprimerRDV.setText("Supprimer RDV");
        menuItemSupprimerRDV.setName("menuItemSupprimerRDV"); // NOI18N
        menuItemSupprimerRDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSupprimerRDVActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemSupprimerRDV);

        jMenuBar1.add(jMenu5);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Folder.gif"))); // NOI18N
        jMenu4.setText("Consultation");

        menuItemAjouterConsultation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/New document.gif"))); // NOI18N
        menuItemAjouterConsultation.setText("Ajouter Consultation");
        menuItemAjouterConsultation.setName("menuItemAjouterConsultation"); // NOI18N
        menuItemAjouterConsultation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAjouterConsultationActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemAjouterConsultation);

        menuItemModifierConsultation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Modify.gif"))); // NOI18N
        menuItemModifierConsultation.setText("Modifier Consultation");
        menuItemModifierConsultation.setName("menuItemModifierConsultation"); // NOI18N
        menuItemModifierConsultation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModifierConsultationActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemModifierConsultation);

        jMenuBar1.add(jMenu4);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Report.gif"))); // NOI18N
        jMenu3.setText("Rapport et Statistiques");

        menuItemOrdonnance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Print.gif"))); // NOI18N
        menuItemOrdonnance.setText("Ordonnance");
        menuItemOrdonnance.setName("menuItemOrdonnance"); // NOI18N
        menuItemOrdonnance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOrdonnanceActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemOrdonnance);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiagnosticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagnosticActionPerformed
        
        
        
    }//GEN-LAST:event_txtDiagnosticActionPerformed

    private void menuItemAjouterMaladeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAjouterMaladeActionPerformed
        // TODO add your handling code here:
        this.setMajMalade("ajouter");
        AjouterModifMalade framedetailsMalade=new AjouterModifMalade(this);
        framedetailsMalade.show();
        
    }//GEN-LAST:event_menuItemAjouterMaladeActionPerformed

    private void menuItemModifierMaladeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModifierMaladeActionPerformed
        // TODO add your handling code here:
        this.setMajMalade("modifier");
        AjouterModifMalade framedetailsMalade=new AjouterModifMalade(this);
        framedetailsMalade.show();
        
    }//GEN-LAST:event_menuItemModifierMaladeActionPerformed

    private void menuItemAjouterConsultationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAjouterConsultationActionPerformed
        // TODO add your handling code here:
        this.setMajConsultation("ajouter");
        AjoutModifConsultation frameDetailsConsultation=new AjoutModifConsultation(this);
        frameDetailsConsultation.show();
    }//GEN-LAST:event_menuItemAjouterConsultationActionPerformed

    private void menuItemModifierConsultationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModifierConsultationActionPerformed
        // TODO add your handling code here:
        this.setMajConsultation("modifier");
        AjoutModifConsultation frameDetailsConsultation=new AjoutModifConsultation(this);
        frameDetailsConsultation.show();
    }//GEN-LAST:event_menuItemModifierConsultationActionPerformed

    private void btAjouterMaladeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterMaladeActionPerformed
        // TODO add your handling code here:
        this.setMajMalade("ajouter");
        AjouterModifMalade framedetailsMalade=new AjouterModifMalade(this);
        framedetailsMalade.show();
        
    }//GEN-LAST:event_btAjouterMaladeActionPerformed

    private void btModifierMaladeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifierMaladeActionPerformed
        // TODO add your handling code here:
        this.setMajMalade("modifier");
        AjouterModifMalade framedetailsMalade=new AjouterModifMalade(this);
        framedetailsMalade.show();
        
    }//GEN-LAST:event_btModifierMaladeActionPerformed

    private void btAjouterRDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterRDVActionPerformed
        // TODO add your handling code here:
        this.setMajRDV("ajouter");
        this.setIdp(trdv[tableMalade.getSelectedRow()]);
        AjoutModifRDV frameAjoutModifRDV =new AjoutModifRDV(this);
        frameAjoutModifRDV.show();
        
    }//GEN-LAST:event_btAjouterRDVActionPerformed

    private void btModifierRDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifierRDVActionPerformed
        // TODO add your handling code here:
        this.setMajRDV("modifier");
        this.setIdRDV(this.trdv[tableRDV.getSelectedRow()]);
        AjoutModifRDV frameDetailsRDV=new AjoutModifRDV(this);
        frameDetailsRDV.show();
    }//GEN-LAST:event_btModifierRDVActionPerformed

    private void btImprimerOrdonnanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimerOrdonnanceActionPerformed
        // TODO add your handling code here:
        this.setIdp(this.tp[tableMalade.getSelectedRow()]);
        this.setIdRDV(this.trdv[tableRDV.getSelectedRow()]);
        CtrlImprimerOrdonnance ctrlImprimerOrdonnance= new CtrlImprimerOrdonnance(this);
        ctrlImprimerOrdonnance.RemplirOrdonnance();
    }//GEN-LAST:event_btImprimerOrdonnanceActionPerformed

    private void btSupprimerMaladeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprimerMaladeActionPerformed
        // TODO add your handling code here:
        this.setIdp(this.tp[tableMalade.getSelectedRow()]);
        CtrlSupprimerPatient ctrlSupprimerPatient= new CtrlSupprimerPatient();
        ctrlSupprimerPatient.supprimerPatient(this.getIdp());
        remplirtableMalade();
    }//GEN-LAST:event_btSupprimerMaladeActionPerformed

    private void btSupprimerRDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprimerRDVActionPerformed
        // TODO add your handling code here:
        this.setIdRDV(this.trdv[tableRDV.getSelectedRow()]);
        CtrlSupprimerRDV ctrlSupprimerRDV= new CtrlSupprimerRDV();
        ctrlSupprimerRDV.supprimerRDV(this.getIdRDV());
        remplirTableRdvByTableMalade();
        
    }//GEN-LAST:event_btSupprimerRDVActionPerformed

    private void btAjouterConsultationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterConsultationActionPerformed
        // TODO add your handling code here:
        this.setMajConsultation("ajouter");
        AjoutModifConsultation frameDetailsConsultation=new AjoutModifConsultation(this);
        frameDetailsConsultation.show();
    }//GEN-LAST:event_btAjouterConsultationActionPerformed

    private void btModifierConsultationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifierConsultationActionPerformed
        // TODO add your handling code here:
        this.setMajConsultation("modifier");
       AjoutModifConsultation frameDetailsConsultation=new AjoutModifConsultation(this);
        frameDetailsConsultation.show();
    }//GEN-LAST:event_btModifierConsultationActionPerformed

    private void menuItemQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemQuitterActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_menuItemQuitterActionPerformed

    private void menuItemSupprimerMaladeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSupprimerMaladeActionPerformed
        // TODO add your handling code here:
        this.setIdp(this.tp[tableMalade.getSelectedRow()]);
        CtrlSupprimerPatient ctrlSupprimerPatient= new CtrlSupprimerPatient();
        ctrlSupprimerPatient.supprimerPatient(this.getIdp());
        remplirtableMalade();
    }//GEN-LAST:event_menuItemSupprimerMaladeActionPerformed

    private void menuItemAjouterRDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAjouterRDVActionPerformed
        // TODO add your handling code here:
        this.setMajRDV("ajouter");
        this.setIdp(trdv[tableMalade.getSelectedRow()]);
        AjoutModifRDV frameDetailsRDV=new AjoutModifRDV(this);
        frameDetailsRDV.show();
        
    }//GEN-LAST:event_menuItemAjouterRDVActionPerformed

    private void menuItemModifierRDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModifierRDVActionPerformed
        // TODO add your handling code here:
        this.setMajRDV("modifier");
        this.setIdRDV(this.trdv[tableRDV.getSelectedRow()]);
        AjoutModifRDV frameDetailsRDV=new AjoutModifRDV(this);
        frameDetailsRDV.show();
    }//GEN-LAST:event_menuItemModifierRDVActionPerformed

    private void menuItemSupprimerRDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSupprimerRDVActionPerformed
        // TODO add your handling code here:
        this.setIdRDV(this.trdv[tableRDV.getSelectedRow()]);
        CtrlSupprimerRDV ctrlSupprimerRDV= new CtrlSupprimerRDV();
        ctrlSupprimerRDV.supprimerRDV(this.getIdRDV());
        remplirTableRdvByTableMalade();
    }//GEN-LAST:event_menuItemSupprimerRDVActionPerformed

    private void menuItemOrdonnanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOrdonnanceActionPerformed
        // TODO add your handling code here:
        this.setIdp(this.tp[tableMalade.getSelectedRow()]);
        this.setIdRDV(this.trdv[tableRDV.getSelectedRow()]);
        CtrlImprimerOrdonnance ctrlImprimerOrdonnance= new CtrlImprimerOrdonnance(this);
        ctrlImprimerOrdonnance.RemplirOrdonnance();
    }//GEN-LAST:event_menuItemOrdonnanceActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        FrameConnexion frameConnexion = new FrameConnexion();
        frameConnexion.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    public String getMajMalade() {
		return majMalade;
    }
    public String getMajConsultation() {
		return majConsultation;
    }
    public String getMajRDV() {
		return majRDV;
    }

    public JTable getTableMalade() {
        return tableMalade;
    }

    public int getIdm() {
        return idm;
    }

    public void setMajMalade(String majMalade) {
        this.majMalade = majMalade;
    }

    public void setMajConsultation(String majConsultation) {
        this.majConsultation = majConsultation;
    }

    public void setMajRDV(String majRDV) {
        this.majRDV = majRDV;
    }

    public int getIdp() {
        return idp;
    }   

    public void setIdp(int idp) {
        FenPrincipale.idp = idp;
    }
    
    public JTable getTableRDV() {
        return tableRDV;
    }

    public int getIdRDV() {
        return idRDV;
    }

    public void setIdRDV(int idRDV) {
        FenPrincipale.idRDV = idRDV;
    }

    public JTextField getTxtDiagnostic() {
        return txtDiagnostic;
    }

    public JTextArea getTxtMotif() {
        return txtMotif;
    }

    public JTextArea getTxtResExamClinique() {
        return txtResExamClinique;
    }

    public JTextArea getTxtResExamParaclinique() {
        return txtResExamParaclinique;
    }

    public JTextArea getTxtTraitement() {
        return txtTraitement;
    }    
        
    public void remplirtableMalade(){ 
        ResultSet Rs;
        connexionBD con = new connexionBD();
        dt = new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Prenom", "Date Naissance", "Telephone", "Sexe", "Situation familiale", "Profession", "Assuré", "Adresse"
            }
        );
        tableMalade.setModel(dt);
        tableMalade.getTableHeader().setReorderingAllowed(false);
        jScrollTableMalade.setViewportView(tableMalade);
        try{
            dt.setRowCount(0);
            Rs =con.reqSelection("Select * From patient where idMedecin="+this.getIdm());
            tp = new int[100];
        	int i=0;
            while(Rs.next()){
                tp[i]=Rs.getInt("codePatient");
                Nom = Rs.getString("nomPatient");
                Prenom = Rs.getString("prenomPatient");
                Date_Naissance = Rs.getDate("dateNaissance");
                Telephone = Rs.getInt("telPatient");
                Sexe = Rs.getString("Sexe");
                Situation_familiale = Rs.getString("situationFamiliale");
                Profession = Rs.getString("profession");
                Assure = Rs.getBoolean("assure");
                Adresse = Rs.getString("adressePatient");
                Object[] objPatient={Nom,Prenom,Date_Naissance,Telephone,Sexe,Situation_familiale,Profession,Assure,Adresse};
                dt.addRow(objPatient);
                i +=1 ;
            }
        }catch(Exception e){
        	JOptionPane.showMessageDialog(null,"Erreur afficher la liste de patients\n"+e.getMessage());
        }  
    }
    public void remplirTableRdvByTableMalade(){
        ResultSet Rs;
        connexionBD con = new connexionBD();
        dt1 = new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date RDV", "Numero RDV"
            }
        );
        tableRDV.setModel(dt1);
        tableRDV.getTableHeader().setReorderingAllowed(false);
        jScrollTableRDV.setViewportView(tableRDV);
        try{
            dt1.setRowCount(0);
            Rs =con.reqSelection("Select * From rdv where idMedecin="+this.getIdm()+" and codePatient="+this.tp[tableMalade.getSelectedRow()]);
            trdv = new int[100];
            int i=0; 
            while(Rs.next()){
                trdv[i]=Rs.getInt("codeRDV");
                Numero_RDV = Rs.getInt("numRDV");
                Date_RDV = Rs.getDate("dateRDV");
                Object[] objRDV={Date_RDV,Numero_RDV};
                dt1.addRow(objRDV);
                i +=1 ;
            }
        }catch(Exception e){
        }  
    }
    public void afficheInfosConsultationByTableRDV(){
        ResultSet Rs;
        connexionBD con = new connexionBD();
        try{
            Rs =con.reqSelection("Select * From Consultation where codeRDV="+this.trdv[tableRDV.getSelectedRow()]);
            Rs.next();
            if(Rs.getRow()!=0){
                this.txtMotif.setText(Rs.getString("motif"));
                this.txtResExamClinique.setText(Rs.getString("resultExamClinique"));
                this.txtResExamParaclinique.setText(Rs.getString("resultExamParaclinique"));
                this.txtTraitement.setText(Rs.getString("traitementPatient"));
                this.txtDiagnostic.setText(Rs.getString("diagnostic"));
            }else{
                this.txtMotif.setText("");
                this.txtResExamClinique.setText("");
                this.txtResExamParaclinique.setText("");
                this.txtTraitement.setText("");
                this.txtDiagnostic.setText("");
            }
        }catch(Exception e){}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenPrincipale(idm).setVisible(true);
            }
        });
    }
    
    
    private String majMalade;
    private String majConsultation;
    private String majRDV;
    private DefaultTableModel dt;
    private DefaultTableModel dt1;
    private int tp[];
    private int trdv[];
    private String Nom;
    private String Prenom;
    private Date Date_Naissance;
    private int Telephone;
    private String Sexe;
    private String Situation_familiale;
    private String Profession;
    private Boolean Assure;
    private String Adresse;
    private Date Date_RDV;
    private int Numero_RDV;
    private String nomMedecin;
    private static int idm;
    private static int idp;
    private static int idRDV;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjouterConsultation;
    private javax.swing.JButton btAjouterMalade;
    private javax.swing.JButton btAjouterRDV;
    private javax.swing.JButton btAnnulerFiltre;
    private javax.swing.JButton btFiltrer;
    private javax.swing.JButton btImprimerOrdonnance;
    private javax.swing.JButton btModifierConsultation;
    private javax.swing.JButton btModifierMalade;
    private javax.swing.JButton btModifierRDV;
    private javax.swing.JButton btSupprimerMalade;
    private javax.swing.JButton btSupprimerRDV;
    private javax.swing.JComboBox comboFiltre;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollTableMalade;
    private javax.swing.JScrollPane jScrollTableRDV;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuItemAjouterConsultation;
    private javax.swing.JMenuItem menuItemAjouterMalade;
    private javax.swing.JMenuItem menuItemAjouterRDV;
    private javax.swing.JMenuItem menuItemModifierConsultation;
    private javax.swing.JMenuItem menuItemModifierMalade;
    private javax.swing.JMenuItem menuItemModifierRDV;
    private javax.swing.JMenuItem menuItemOrdonnance;
    private javax.swing.JMenuItem menuItemParamImp;
    private javax.swing.JMenuItem menuItemQuitter;
    private javax.swing.JMenuItem menuItemSupprimerMalade;
    private javax.swing.JMenuItem menuItemSupprimerRDV;
    private javax.swing.JTable tableMalade;
    private javax.swing.JTable tableRDV;
    private javax.swing.JTextField txtDiagnostic;
    private javax.swing.JTextField txtFiltre;
    private javax.swing.JTextArea txtMotif;
    private javax.swing.JTextArea txtResExamClinique;
    private javax.swing.JTextArea txtResExamParaclinique;
    private javax.swing.JTextArea txtTraitement;
    // End of variables declaration//GEN-END:variables
}